name: balkans
favicon: null
layout_spectrum: 0.21717
typography_spectrum: 0.31903
title: A trip to the Balkans
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c3ddf4'
    - '#1276ce'
    - '#000800'
    - '#647a6d'
    - '#de8664'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
