name: balkans
favicon: null
layout_spectrum: 0.48241359065286815
typography_spectrum: 0.8313464219681919
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.27593443915247917
  lightness: 0.15074469964019954
  saturation: 0.9465566242579371
  rhythmicContrast: 0.31023933878168464
purpose: []
